### PR TITLE
port to fabric bulk

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Be sure to make a new fabric branch from 1.19.x branch and change this PR to that fabric branch. This ports everything except for the chest explorer map code. That one you'll have to figure out as I am not sure what the fabric equivalent is for chest content stuff. I also ported to using Midnight lib to get something compliable but you can switch to a different config lib or stuff (I did not add translations for all the config values for midnight lib)

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
Tested with locate command far in-land for buried treasure and looks like it is working

**Comment by mocksonline** [comment]
Please give a jar file, the one I compiled with myself crashes on startup (only fabric api, this module and Midnight lib, all versions crash) looks like a mixin issue.
https://pastebin.com/b8idgSTs

**Comment by thebrightspark** [comment]
@mocksonline There's no point providing a JAR file at this point... I still need to get round to finishing this port off. I've just had little free time unfortunately.

**Comment by thebrightspark** [comment]
I decided to use the multi-loader structure for the mod to support both Forge and Fabric easily in the same project 😄 
Greatly appreciate the efforts here though, they helped with my port regardless!

**Pull request closed without merging**
